apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
	namespace: my-ns
spec:
  serviceAccountName: k8s-sa   # service account
  securityContext: #  define runAsNonRoot, allowPrivilegeEscalation, readOnlyRootFilesystem, selinux, seccomp PER CONTAINER  
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000   # supplementary group
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:   # for this container only, can also have runasuser/runasgroup
      privileged: false
      allowPrivilegeEscalation: false     
      readOnlyRootFilesystem: true     # only in container
      capabilities:  # linux capabilities
        add: ["NET_ADMIN", "SYS_TIME"]
      appArmorProfile:   # 
        type: Localhost  # RuntimeDefault # Unconfined 
        localhostProfile: k8s-apparmor-example-deny-write	  # installed PROFILE name
      seccompProfile:
        type: Localhost
        localhostProfile: profiles/audit.json   # default dir /var/lib/kubelet/seccomp
