apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:   # to match node labels
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
    nodeAffinity:   # to match node labels
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
      # to schedule to the node where pod app=web-store doesn't run
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - web-store
          topologyKey: "kubernetes.io/hostname"
      # to prefer to chedule to the node where pod security=S2 runs
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - S2
            topologyKey: topology.kubernetes.io/zone          
  tolerations: # kubectl taint nodes node1 key1=value1:NoSchedule
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"  
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"  
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
