apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: default  # namespaced
spec:
  storageClassName: manual # to match PV class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
