apiVersion: v1
kind: PersistentVolume
metadata:   # not namespaced resource
  name: mypv
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain # Delete 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
    - ReadWriteMany
    #- ReadOnlyMany
    #- ReadWriteOncePod
  hostPath:
    path: "/mnt/data"
